[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	miguelbalboa/MFRC522@^1.4.11
	mobizt/Firebase ESP32 Client@^4.4.14
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit SH110X@^2.1.10
	adafruit/Adafruit PCF8574 @ ^1.1.1
	mandulaj/PZEM-004T-v30 @ ^1.1.2
	beegee-tokyo/DHT sensor library for ESPx @ ^1.19.0
	bblanchon/ArduinoJson @ ^7.0.4